# Generated by Django 5.1.4 on 2024-12-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = []
