# Generated by Django 5.1.4 on 2024-12-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
